version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./Backend/.env
    networks:
      - rag_network

  frontend:
    build:
      context: ./Frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
